name: ledger
description: A ledger application written in Flutter.
repository: https://github.com/AC-Coooooler/flutter_ledger
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  cookie_jar: ^3.0.1
  device_info_plus: ^4.0.0
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  equatable: ^2.0.3
  ff_annotation_route_library: ^3.0.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.6.0
  loading_more_list: ^4.1.2
  logging: ^1.0.2
  oktoast: ^3.2.0
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  pull_to_refresh_notification: ^2.3.0
  url_launcher: ^6.1.5

dev_dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  build_runner: ^2.2.0
  crypto: ^3.0.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  path: ^1.8.1
  process_run: ^0.12.3+2
  yaml: ^3.1.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
