// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import
import 'package:flutter/foundation.dart';
import 'package:ledger/exports.dart';

const List<String> routeNames = <String>[
  'bill-adding-page',
  'bill-page',
  'home-page',
  'splash-page',
];

class Routes {
  const Routes._();

  /// 'bill-adding-page'
  ///
  /// [name] : 'bill-adding-page'
  ///
  /// [constructors] :
  ///
  /// BillAddingPage : [Key? key]
  static const _BillAddingPage billAddingPage = _BillAddingPage();

  /// 'bill-page'
  ///
  /// [name] : 'bill-page'
  ///
  /// [constructors] :
  ///
  /// BillPage : [Key? key, BillModel(required) bill]
  static const _BillPage billPage = _BillPage();

  /// 'home-page'
  ///
  /// [name] : 'home-page'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _HomePage homePage = _HomePage();

  /// 'splash-page'
  ///
  /// [name] : 'splash-page'
  ///
  /// [constructors] :
  ///
  /// SplashPage : [Key? key]
  static const _SplashPage splashPage = _SplashPage();
}

class _BillAddingPage {
  const _BillAddingPage();

  String get name => 'bill-adding-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _BillPage {
  const _BillPage();

  String get name => 'bill-page';

  Map<String, dynamic> d({
    Key? key,
    required BillModel bill,
  }) =>
      <String, dynamic>{
        'key': key,
        'bill': bill,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'home-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _SplashPage {
  const _SplashPage();

  String get name => 'splash-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
